// File: src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TermlyCMP from "./componenent/TermlyCMP";

const WEBSITE_UUID = "acc52775-e3b8-423f-a76e-de49e5d712f7";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TermlyCMP websiteUUID={WEBSITE_UUID} />
        {children}
      </body>
    </html>
  );
}
